### ISSUE TITLE
Cannot set "status_codes" to empty array when creating an uptime test

### ISSUE THREAD

**Issue by G-Rath** [StatusCakeDev/statuscake-go#4]
If you create a new uptime test with an empty array for `status_codes`, the api instead adds all the status codes.

This means you can only remove all statuscodes with an update request.

It would be good if there way a way to tell the api to not create an uptime test with any statuscodes.

**Comment by tomasbasham** [comment]
IIRC an HTTP/HEAD uptime test must have status codes set in order for it to function correctly. So the bug here is the fact they can be removed with an update. In future we may require having to set the status codes explicitly on create. Whilst the StatusCake UI offers the convenience of pre-populating the status codes fields this is not ideal behaviour from the API as has caused issues with our Terraform provider.

I'll close this issue for now as further works needs doing to investigate how to handle these codes properly
